name: android_OTA_make

on:
  watch:
    types: [started]
    
env:
  OLD_ROM_URL: https://cloud189-liaoning-person.oos-lnsy.ctyunapi.cn/PERSONCLOUD/9bc31144-7221-42ab-8c8f-62cacece6551.zip?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=532482dfdc85e5d60592&x-amz-UID=500119206&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22Mz16sPro_MIUI_Q_20.11.22_Donated.zip%22&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D10240%2Cconcurrency%3D20&Signature=B5SeT82Zjjd9M7Z4wH5%2BxFQ0cmE%3D&x-amz-SHID=169945421&Expires=1607108403&x-amz-FSIZE=2566803589&x-amz-UFID=71351112139626423
  NEW_ROM_URL: https://cloud189-liaoning-person.oos-lnsy.ctyunapi.cn/PERSONCLOUD/c548112b-eb24-4ce6-a885-39636dc6edc2.zip?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=532482dfdc85e5d60592&x-amz-UID=500119206&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22Mz16sPro_MIUI_Q_20.11.25_MeizuCamera_Donated.zip%22&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D10240%2Cconcurrency%3D20&Signature=zCOz0w5e3M2ZYWbvAWVTsIxMTVg%3D&x-amz-SHID=169945421&Expires=1607109825&x-amz-FSIZE=2759325324&x-amz-UFID=21423112185203087
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
  
    - name: Initialization environment 
      run: |
        cd ~
        mkdir old-rom
        mkdir new-rom
        mkdir final-rom
        mkdir final
        sudo -E apt-get update
        sudo -E apt-get install wget python python-pip python3 python3-pip
        pip3 install setuptools
        pip3 install bsdiff4
        
    - name: Clean Up Disk Space
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean 
        
    - name: Clone the tools source code
      run: |
       cd ~
       git clone https://github.com/cjybyjk/OTA-maker.git 
  
    - name: Download the old ROM
      run: |
       cd ~
       cd old-rom
       wget -O old-rom.zip $OLD_ROM_URL
   
    - name: Download the new ROM
      run: |
       cd ~
       cd new-rom
       wget -O new-rom.zip $NEW_ROM_URL
    
    - name: make OTA ROM
      run: |
       cd ~
       cd OTA-maker
       python3 makeota.py ~/old-rom/old-rom.zip  ~/new-rom/new-rom.zip ~/final_rom
   
    - name: Zip OTA ROM
      run: |
          zip -r ~/final/OTA.zip ~/final_rom
    
    - name: Upload the OTA ROM to WeTransfer
      run: |
        cd ~
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ~/final/OTA.zip
